title: Rystal Music RPC
header: Rystal Music RPC
toggle_button_image: "toggle.png"
secret_input_placeholder: "Your Secret"
error_text: "Please enter a secret!"
websocket_url: "ws://78.108.218.193:25571"
client_id: "1202320335270334534"
large_image_key: "music_icon"
large_image_text: "Rystal V6"
youtube_label: "Watch on YouTube"
socket_failure: "Failed to connect to socket!"
socket_closed: "Reconnecting to websocket!"
rpc_error: "Failed to connect to rich presence!"